### ISSUE TITLE
Auth Explanation(Xamarin Forms, MAUI)

### ISSUE THREAD

**Issue by Phantom-KNA** [supabase-community/supabase-csharp#100]
### For New Users

[Auth Explanation(Xamarin Forms, MAUI)](https://gist.github.com/Phantom-KNA/0eabbbe52076370489d0ecbf73f0a6c6)

**Comment by acupofjose** [comment]
Thanks @Phantom-KNA! Your work is linked [here](https://github.com/supabase-community/supabase-csharp/wiki/Authorization-with-Gotrue#mauixamarin-examples)

**Comment by Phantom-KNA** [comment]
Thank to you for hard work!!

**Comment by Phantom-KNA** [comment]
> Thanks @Phantom-KNA! Your work is linked [here](https://github.com/supabase-community/supabase-csharp/wiki/Authorization-with-Gotrue#mauixamarin-examples)

Hey @acupofjose , where I can found the TODO List for this project?

**Comment by acupofjose** [comment]
At the moment, we don’t have a public one. If you have a suggestion for good places to host  one, I’m all ears.

**Comment by Phantom-KNA** [comment]
> At the moment, we don’t have a public one. If you have a suggestion for good places to host  one, I’m all ears.

I mean Supabase Sharp, there is no to-do list for developers to join to support. If you need a space I have a domain and you can host it there.

**Comment by Phantom-KNA** [comment]
> At the moment, we don’t have a public one. If you have a suggestion for good places to host  one, I’m all ears.

I mean Supabase Sharp, there is no to-do list for developers to join to support. If you need a space I have a domain and you can host it there.

**Comment by utadluis** [comment]
Thanks for this explanation! It really helped me understand how to handle authentication in MAUI with Supabase
