### ISSUE TITLE
Wont work in Winform?

### ISSUE THREAD

**Issue by cyrsis** [supabase-community/supabase-csharp#106]
# Bug report
Installed the package from nuget, break every system.draw in winform

## Describe the bug
For most of the business application, Winform is essential

## To Reproduce
Create a new project with winform (.net) lastest is 4.6

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

Windows

**Comment by wiverson** [comment]
Try trimming down the libraries to match the same set as in this template - https://github.com/wiverson/supabase-unity-template, specifically down to [this set](https://github.com/wiverson/supabase-unity-template/tree/main/Assets/Supabase). Sometimes NuGet pulls in too many libraries that appear to conflict...

**Comment by RishanR** [comment]
I'm also having the System.Drawing issue after installing supabase-csharp for WinForm. Was anyone able to fix this?

**Comment by RishanR** [comment]
Nevermind, I got it working. Turns out that you have to create a WPF application, not a WinForm. Works perfectly after that :)
