### ISSUE TITLE
Add method to validate a provided JWT

### ISSUE THREAD

**Issue by acupofjose** [supabase-community/supabase-csharp#11]
As mentioned in #7 by @evanrobertson

**Comment by acupofjose** [comment]
As of 0.2.6, a User's JWT can be validated using the StatelessClient
```
using static Supabase.StatelessClient;

var url = "https://1234abcd.supabase.io";
var applicationKey = "1234";

// Forms the appropriate `StatelessClientOptions`
var options = GetAuthOptions(url, applicationKey, options);

var user = await Supabase.Gotrue.StatelessClient.GetApi(options).GetUser("my-user-jwt");
// .. blah blah blah
```

**Comment by MuhammadBilalYar01** [comment]
@acupofjose , here application key mean JWT secret or something different, if not then from where i can this application key

**Comment by acupofjose** [comment]
@MuhammadBilalYar01 this is either your anonymous public key or the service role key found in the Supabase admin panel!
