### ISSUE TITLE
Does not work with Windows Presentation Foundation (WPF)

### ISSUE THREAD

**Issue by pinnouse** [supabase-community/supabase-csharp#116]
# Bug report

## Describe the bug

Added nuget package to app, does not build.

## To Reproduce

1. Create new .NET Framework project
2. Install supabase-csharp package
3. Build

## Expected behavior

Builds and runs normally.

## Screenshots

![image](https://github.com/supabase-community/supabase-csharp/assets/11915698/ec42275e-261c-466d-8a41-c7fc3e2e0aeb)

## System information

- OS: Windows
- Version of supabase-js: [e.g. 6.0.2]

## Additional context

Tried both targeting Framework 4.7.2 and 4.8 as well as a bunch of other workarounds found online such as adding an explicit reference to "netstandard" in the config.

**Comment by acupofjose** [comment]
@pinnouse I can duplicate it, but I have no idea how to fix it. Everything I see online about the types says it's a VS issue, but that doesn't really make sense to me. With targeting `netstandard2.0` I believe it should have support for framework `4.x`? But, like I said, I don't know how to fix the build error, it's outside what I've used C# for in the past.

**Comment by wiverson** [comment]
I *think* this sort of thing arises from having NuGet pull down conflicting libraries. When you target netstandard2.0 my observation has been that NuGet will pull down a bunch of extra libraries that will generate conflicts with other .NET versions.

For example, here is a [trimmed down set of libs](https://github.com/wiverson/supabase-unity-template/tree/main/Assets/Supabase) that I use for Unity. You might try manually deleting some of the libraries (esp System.* ones) and see if that helps.
