### ISSUE TITLE
Send Valid User Access Token to Realtime Server

### ISSUE THREAD

**Issue by w3b6x9** [supabase-community/supabase-csharp#12]
# Feature request

Realtime server is now checking every minute to verify the validity of the user access token and storing updated user information from the JWT to Realtime's `subscription` table (used by Realtime WALRUS).

## Describe the solution you'd like

1. Realtime client pushes the user access token to all channels every heartbeat, which defaults to 30 seconds (see [ref](https://github.com/supabase/realtime-js/pull/116), [ref](https://github.com/supabase/realtime-js/pull/117), and [ref](https://github.com/supabase/realtime-js/pull/119)).
2. Supabase client sends latest and valid user access token on auth events `SIGNED_IN` and `TOKEN_REFRESHED` (see [ref](https://github.com/supabase/supabase-js/blob/5034d6fb8b2337d6893cfcc97781432a33b0649a/src/SupabaseClient.ts#L271))*.
3. Supabase client removes all subscriptions on auth event `SIGNED_OUT` (see [ref](https://github.com/supabase/supabase-js/blob/5034d6fb8b2337d6893cfcc97781432a33b0649a/src/SupabaseClient.ts#L281))*.

*[fix: improve auth for realtime row level security #303](https://github.com/supabase/supabase-js/pull/303)

## Additional context

Realtime Security (WALRUS) will be launched very soon so we'll mention that additional Supabase client libs, like this one, will be compatible with the new Realtime some time in the near future.

**Comment by acupofjose** [comment]
@w3b6x9 thanks for the heads up! Unless I'm missing something, I don't see any of those events tied to the heartbeat function. Is it a one time push? Or every heartbeat?

**Comment by w3b6x9** [comment]
@acupofjose awesome! You already figured it out but just to clarify `realtime-js` calls [setAuth](https://github.com/supabase/realtime-js/blob/9aed05d79972b00a5c988419735865d4f343786f/src/RealtimeClient.ts#L326) in [_sendHeartbeat](https://github.com/supabase/realtime-js/blob/9aed05d79972b00a5c988419735865d4f343786f/src/RealtimeClient.ts#L398), which is called every [heartbeat interval](https://github.com/supabase/realtime-js/blob/9aed05d79972b00a5c988419735865d4f343786f/src/RealtimeClient.ts#L393).

**Comment by acupofjose** [comment]
@w3b6x9 it doesn't look like `USER_DELETED` is implemented in gotrue-js (https://github.com/supabase/gotrue-js/search?q=USER_DELETED) is that correct?

**Comment by w3b6x9** [comment]
> @w3b6x9 it doesn't look like `USER_DELETED` is implemented in gotrue-js (https://github.com/supabase/gotrue-js/search?q=USER_DELETED) is that correct?

@acupofjose good catch! Looks like it's not implemented yet. I'll remove it from this feature request.

**Comment by acupofjose** [comment]
Available in 0.2.6!
