### ISSUE TITLE
Update Realtime user_token after fresh token event

### ISSUE THREAD

**Issue by w3b6x9** [supabase-community/supabase-csharp#13]
Just wanted to point out that there's a recent `realtime-js` fix that will update the `user_token` used for channel (subscription) reconnection: https://github.com/supabase/realtime-js/pull/126.

**Comment by acupofjose** [comment]
Awesome - I'll get on this tomorrow. Thanks @w3b6x9!

**Comment by w3b6x9** [comment]
@acupofjose awesome, thank you!

**Comment by acupofjose** [comment]
Available in 0.2.11
