### ISSUE TITLE
Postgrest.Exceptions.PostgrestException: {"code":"42883","details":null,"hint":"No operator matches the given name and argument types. You might need to add explicit type casts.","message":"operator does not exist: text @> unknown"} Dotnet Supabase

### ISSUE THREAD

**Issue by joseadrianoemmanuel1999** [supabase-community/supabase-csharp#140]
# Bug report
"code":"42883"
## Describe the bug
I am trying to use this command in my project :
```c#
await _SupabaseClient
                      .From<Products>()
                      .Select("id,name,price,desc,brand_id:Brands(id,name),subcategory_id:Subcategories(id,name,category_id:Categories(id,name,gender)),Imgs(image),shop_id:users(id,fullname)")
                      .Filter(x=>x.brand_id.name.ToString(),Operator.Contains,new List<Object> {"Nike","Puma"}).Get();
```
When i try use have this is error:
```bash
Postgrest.Exceptions.PostgrestException: {"code":"42883","details":null,"hint":"No operator matches the given name and argument types. You might need to add explicit type casts.","message":"operator does not exist: text @> unknown"}
```

## System information

- OS: [ Windows]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Dotnet : [7]

**Comment by acupofjose** [comment]
Hm. Seems like something is not being translated into the query correctly... it should be using the operators like specified [here](https://postgrest.org/en/stable/references/api/tables_views.html#operators). 

Off the top of my head, I wonder if `?tags=cs.{example, new}` is being sent incorrectly as `?tags=cs.{"example", "new"}`.

Could you try the `In` operator instead and see if that works?

**Comment by joseadrianoemmanuel1999** [comment]
Thanks to respond me, Yes i try use operator In and nothing is working.

**Comment by acupofjose** [comment]
I'm able to duplicate, but I'm not sure what the issue is with the `CONTAINS` operator. The request is being formed according to their documentation. I'm going to open an issue on the postgrest repo and see if they have an issue.

It looks like the functionality you're looking for is available using the `IN` operator though.

The following test case works (relative to the `PostgrestTests` part of the repo) as expected:
```c#
[TestMethod("filters: cs (list)")]
public async Task TestContainsFilterList()
{
    var client = new Client(BaseUrl);

    var filteredResponse = await client.Table<User>()
        .Filter(x => x.Username!, Operator.In, new List<string> { "dragarcia", "acupofjose" })
        .Get();

    filteredResponse.Models.ForEach(x => Assert.IsTrue(x.Username is "dragarcia" or "acupofjose"));
}
```

**Comment by acupofjose** [comment]
@joseadrianoemmanuel1999 the answer given the issue:

> The contains operator @> does not work for text types. It's used for arrays, json(b) and others. Are you trying to query all the users with username that belong to a list of candidates? If so you can use [like(any)](https://postgrest.org/en/latest/references/api/tables_views.html#operator-modifiers).

So please use the `IN` or `LIKE` operator!

**Comment by joseadrianoemmanuel1999** [comment]
It's worked but it's sad other command fails, But thanks for help
