### ISSUE TITLE
Return ModeledResponse for calling a Postgres Function/Stored Procedure

### ISSUE THREAD

**Issue by Katerlad** [supabase-community/supabase-csharp#147]
# Feature request
Quality of Life feature to allow "ModeledResponse" response to calling a Postgres Function/Stored Procedure. 
- Currently the response is of type "BaseResponse" and we have to manually cast to the model we want ourselves. 

## Describe the solution you'd like

Please create a way to easily convert the response of a Stored Procedure into a C# model! My Initial thought is to allow you to pass a type parameter with the function call!

ModeledResponse< MyModel > response = await supabase.rpc< MyModel>(null, params);

## Additional context

If implemented, this all started with poor documentation to the "calling postgres functions" located here https://supabase.com/docs/reference/csharp/rpc?example=call-a-stored-procedure

Please make sure to update documentation to reflect these changes if implemented.

**Comment by acupofjose** [comment]
Available in 0.16.1!
