### ISSUE TITLE
Gotrue-csharp SignOut() by scope

### ISSUE THREAD

**Issue by kienns1996** [supabase-community/supabase-csharp#148]
# Feature request

## Is your feature request related to a problem? Please describe.

Is it possible to add a scope option to be able to logout "local", "global" or "others" in Gotrue-csharp?
SignOut() logs out all sessions by default.

**Comment by acupofjose** [comment]
The client is designed to only support one user per client instance, if you need to support multiple signed in users at a time, you'll need to initialize a separate client for the secondary user as well as a different `GotrueSessionPersistence` handler if you're attempting to persist each user.

As for restructuring the gotrue client to multiple logins within a single instance, that is not something that is planned!

**Comment by acupofjose** [comment]
Available in >= `Supabase.Gotrue@5.0.6`
