### ISSUE TITLE
SignUpWithEmail vs CreateUser Metadata

### ISSUE THREAD

**Issue by fplaras** [supabase-community/supabase-csharp#15]
Hello, comparing the CreateUser and SignUp methods for metadata the implementation seems to be different. 
CreateUser method signature expects an object to be bound to a "data" property and the SignUp method signature is expecting a Dictionary of <string, object> to be bound to the "data" property. Wasn't sure if this was a bug. 

param: Dictionary<string, object> metadata
`Dictionary<string, object> data = new Dictionary<string, object>
            {
                {
                    "email",
                    email
                },
                {
                    "password",
                    password
                },
                {
                    "data",
                    metadata
                }
            };`

param: object userData
`Dictionary<string, object> dictionary = new Dictionary<string, object>
            {
                {
                    "email",
                    email
                },
                {
                    "password",
                    password
                }
            };
            if (userData != null)
            {
                dictionary.Add("data", userData);
            }`

**Comment by acupofjose** [comment]
Oh my! Great catch. Yes, the `CreateUser` call is supposed to have a different format. I'll get that fixed and a test added. Thank you!

**Comment by fplaras** [comment]
@acupofjose this is the metadata result for the new SignUp(). Is this correct?
` "userMetadata": {
    "data": {
      "full_name": []
    },
    "redirectTo": "https://google.com"
  }`
