### ISSUE TITLE
VerifyOTP using token_hash

### ISSUE THREAD

**Issue by tiagomn** [supabase-community/supabase-csharp#160]
Hi Guys

I've tried to find an equivalent method in c# to login using token_hash for recovery purposes. But I haven't found anything related to this piece of code in Javascript:

supabase.auth.verifyOtp({ token_hash: $scope.token_hash, type: 'recovery' }).then(({ data, error })

I would like to use this approach because we wouldn't need to use e-mail address, as we are worried about security issues.

**Comment by acupofjose** [comment]
Available in >= `Supabase.Gotrue@5.0.6`
