### ISSUE TITLE
[MAUI iOS] Failed to AOT compile Microsoft.VisualStudio.TestPlatform.Common.dll

### ISSUE THREAD

**Issue by nor0x** [supabase-community/supabase-csharp#163]
# Bug report
I'm using Supabase in a .NET MAUI app. Publishing a release build for iOS currently breaks with the following error:
 
```js
Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.6/Sdk/../tools/mono-aot-cross execution finished (exit code = 1).        
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile Microsoft.VisualStudio.TestPlatform.Common.dll, the AOT compiler exited with code 1. [/Users/dev/mauisupabase/mauisupabase.csproj::TargetFramework=net8.0-ios]

Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/8.0.6/Sdk/../tools/mono-aot-cross execution finished (exit code = 1).          
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 1. [/Users/dev/mauisupabase/mauisupabase.csproj::TargetFramework=net8.0-ios]
```
I'm not quite sure where `Microsoft.VisualStudio.TestPlatform.Common.dll` is referenced, maybe from https://github.com/supabase-community/storage-csharp?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. dotnet new maui
2. dotnet add package Supabase --version 1.0.4
3. dotnet publish PROJECTNAME.csproj -c Release -f net8.0-ios -r ios-arm64 -p:ArchiveOnBuild=true

## Expected behavior

a published iOS app :-)

## System information

- OS: macOS 14
- Version of supabase: 1.0.4

**Comment by acupofjose** [comment]
I think you may be right on that one! Those dependencies aren't really needed for `Supabase.Storage` I've removed them in the latest release - try 1.0.5 and get back to me?

**Comment by nor0x** [comment]
thank you @acupofjose 
i can confirm that 1.0.5 works fine
