### ISSUE TITLE
Received an error after upgrading from v0.2.12 to v0.3.0

### ISSUE THREAD

**Issue by CodeWithMK** [supabase-community/supabase-csharp#19]
Error message:
`System.MissingMethodException: 'Method not found: 'Void Postgrest.Attributes.ColumnAttribute..ctor(System.String)'.'`

Table class:
```
[Table("users")]
public class User : SupabaseModel
{
    [PrimaryKey("id")]
    public long Id { get; set; }

    [Column("user_name")]
    public string UserName { get; set; }
}
```
The line causing the error:
`var users = await instance.From<User>().Get();`

Am I missing something?

**Comment by acupofjose** [comment]
hm. That's a new one - could you do a full clean, remove the `supabase-csharp` package, and reinstall it and see if that fixes it? If not, try adding a nuget reference to `postgrest-csharp@2.0.6`. It looks like it's not detecting the package.

**Comment by CodeWithMK** [comment]
Full clean up did the trick, I guess it was using an older version. It is fixed now, thanks.
