### ISSUE TITLE
Entity Framework Code First Approach Example

### ISSUE THREAD

**Issue by MuhammadBilalYar01** [supabase-community/supabase-csharp#22]
I am trying to implement this [Youtube Video ](https://youtu.be/qY_iQ10IUhs?t=149) using EF code first approach, can you provide an example of how I can create a relationship between **auth.user** table and **public.LeaderBorad** table

Assuming i have this class for Leaderboard

```
Public class LeaderBoard{
public int score {get;set;}
}
```

Do I need to create a class for  Auth.User table? or superbase already provide some any class?

**Comment by acupofjose** [comment]
@MuhammadBilalYar01 - you can follow the guide here: https://supabase.com/docs/guides/auth/managing-user-data.

But adapting that, you would need to create a new table in the Supabase Admin Panel:
```sql
create table public.leaderboard (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid references auth.users not null,
  score int,
  # etc.
)
```

As for representing `auth.user`? This library does not provide currently provide a class to do so - the `auth.user` table is left open for users to tamper with, but mostly acts as an internal representation of a user. 

Yes, you can represent this as:

```c#
[Table("leaderboard")]
public class LeaderBoard : BaseModel {
  [PrimaryKey("id", false)]
  public string Id { get; set;} 

  [Column("user_id")]
  public string UserId {get; set;}

  [Column("score")]
  public int Score {get; set;}
}
```

Then you can do your normal queries:
```c#
var entries = await Supabase.Client.Instance.From<Models.LeaderBoard>()
                .Filter("user_id", Operator.Equals, user_id)
                .Get();
```
