### ISSUE TITLE
Unity client

### ISSUE THREAD

**Issue by kamyker** [supabase-community/supabase-csharp#25]
Hi, I think Supabase could be a great Firebase replacement especially in Unity as they use a lot of native code making their client supported only on Android and iOS.

Websockets used in supabase-csharp are much more cross-platform. They even work in browser webgl builds.

With that being said I'm up to make Unity specific repo that combines all cs sdks and dependencies as Nuget doesn't work in Unity. Is there any good way of combining github repos? If not I'll simply add all of them as submodules and write simple net console app that copies all required files

**Comment by acupofjose** [comment]
That would be awesome! I think the easiest (and cleanest) way would be to use submodules.

**Comment by kamyker** [comment]
Got it working. Not sure if GetAssemblyVersion() works correctly but I'll skip it until it start causing any errors. 

https://github.com/kamyker/supabase-unity

**Comment by kamyker** [comment]
Np, thanks for your quick fixes too :) @acupofjose
