### ISSUE TITLE
Client instance in Blazor WASM authentication state provider is always null

### ISSUE THREAD

**Issue by diego81b** [supabase-community/supabase-csharp#26]
Hi,

i need to override the default authentication state provider in a Blazor WASM application using this code
```c#
public class CustomAuthenticationStateProvider : AuthenticationStateProvider
    {
        public CustomAuthenticationStateProvider()
        {
        }

        public override Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var identity = new ClaimsIdentity();
            var instance = SupabaseWrapper.ClientInstance;
            var token = instance?.Auth?.CurrentSession?.AccessToken ?? "";

            if (tokenHandler.CanReadToken(token))
            {
                var jwtSecurityToken = tokenHandler.ReadJwtToken(token);
                identity = new ClaimsIdentity(jwtSecurityToken.Claims, "jwt");
            }

            var principal = new ClaimsPrincipal(identity);
            var authenticationState = new AuthenticationState(principal);
            var authenticationTask = Task.FromResult(authenticationState);

            return authenticationTask;
        }
    }
```
This method `GetAuthenticationStateAsync` is called by the framework on route change and always the instance is null
`SupabaseWrapper.ClientInstance` is only a static wrapper around the library to expose the methods

```c#
public static class SupabaseWrapper
    {
        static SupabaseWrapper()
        {
            var url = "https://123456789.supabase.co";
            var key = "123456789";
            Client.Initialize(url, key);
        }

        public static Client ClientInstance => Client.Instance; 

        public static async Task<List<PlannerEvent>> GetEvents()
        {
            try
            {
                var events = await ClientInstance.From<PlannerEvent>().Get();
                return events.Models;
            }
            catch (Exception ex)
            {
                return new List<PlannerEvent>();
            }
        }

        public static async Task Login(string username, string password)
        {
            try
            {
                var session = await ClientInstance.Auth.SignIn(username, password);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public static async Task Register(string username, string password)
        {
            try
            {
                var session = await ClientInstance.Auth.SignUp(username, password);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
```

On the rest of the application the client seems initialized (i have not already tested all aspects)

thanks fo all
Diego

**Comment by acupofjose** [comment]
@diego81b in your debugging, is the token available after retrieving the session  in `Login(string username, string password)`?

If it is, I would wonder if you need to specify the `SessionPersistor` and `SessionRetriever` functions on the `Auth.ClientOptions` writing the session to browser's LocalStorage and retrieving it from there. (That is, unfortunately, not built in functionality!)

**Comment by acupofjose** [comment]
@diego81b sorry I've been slow getting back to you - I'm not super familiar with Blazor. I'm going to try and spin up a project today to help debug this and find an answer!

**Comment by acupofjose** [comment]
Okay - this will be a longer post but here's what I have this working (logging in users, persisting sessions, etc.)

First, in your `Program.cs` we need to add Authorization, LocalStorage (for persistence, I'm using `Blazored.LocalStorage`) and setup the instance.

**Program.cs**
```c#
// ... Imports above

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddBlazoredLocalStorage();
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider, SupabaseAuthStateProvider>();

var host = builder.Build();

#region Supabase

var url = "" // SUPABASE_URL;
var key = "" // ANON API KEY;
var authStorageKey = "supa:session";
var storage = host.Services.GetRequiredService<ILocalStorageService>();
var options = new SupabaseOptions
{
    SessionPersistor = async (session) =>
    {
        await storage.SetItemAsStringAsync(authStorageKey, JsonConvert.SerializeObject(session));
        return true;
    },
    SessionDestroyer = async () =>
    {
        await storage.RemoveItemAsync(authStorageKey);
        return true;
    },
    SessionRetriever = async () =>
    {
        var exists = await storage.ContainKeyAsync(authStorageKey);
        if (exists)
        {
            var str = await storage.GetItemAsStringAsync(authStorageKey);
            return JsonConvert.DeserializeObject<Session>(str);
        }
        return null;
    }
};
Supabase.Client.Initialize(url, key, options);

await host.RunAsync();
```

The `AuthenticationStateProvider` can be adjusted to use the singleton built in to the Supabase Client:

**SupbaseAuthStateProvider.cs**
```c#
public class SupabaseAuthStateProvider : AuthenticationStateProvider
    {
        public override Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var identity = new ClaimsIdentity();
            var instance = Supabase.Client.Instance; // <----
            var token = instance?.Auth?.CurrentSession?.AccessToken ?? "";

            if (tokenHandler.CanReadToken(token))
            {
                var jwtSecurityToken = tokenHandler.ReadJwtToken(token);
                identity = new ClaimsIdentity(jwtSecurityToken.Claims, "jwt");
            }

            var principal = new ClaimsPrincipal(identity);
            var authenticationState = new AuthenticationState(principal);
            var authenticationTask = Task.FromResult(authenticationState);

            return authenticationTask;
        }
    }
```

As for the `Wrapper` class you wrote, you should just reference `Supabase.Client.Instance` directly, because it is already a singleton - otherwise that code in there should work just fine for you!

**Comment by diego81b** [comment]
> Okay - this will be a longer post but here's what I have this working (logging in users, persisting sessions, etc.)
> 
> First, in your `Program.cs` we need to add Authorization, LocalStorage (for persistence, I'm using `Blazored.LocalStorage`) and setup the instance.
> 
> **Program.cs**
> 
> ```cs
> // ... Imports above
> 
> var builder = WebAssemblyHostBuilder.CreateDefault(args);
> builder.RootComponents.Add<App>("#app");
> builder.RootComponents.Add<HeadOutlet>("head::after");
> 
> builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
> builder.Services.AddBlazoredLocalStorage();
> builder.Services.AddAuthorizationCore();
> builder.Services.AddScoped<AuthenticationStateProvider, SupabaseAuthStateProvider>();
> 
> var host = builder.Build();
> 
> #region Supabase
> 
> var url = "" // SUPABASE_URL;
> var key = "" // ANON API KEY;
> var authStorageKey = "supa:session";
> var storage = host.Services.GetRequiredService<ILocalStorageService>();
> var options = new SupabaseOptions
> {
>     SessionPersistor = async (session) =>
>     {
>         await storage.SetItemAsStringAsync(authStorageKey, JsonConvert.SerializeObject(session));
>         return true;
>     },
>     SessionDestroyer = async () =>
>     {
>         await storage.RemoveItemAsync(authStorageKey);
>         return true;
>     },
>     SessionRetriever = async () =>
>     {
>         var exists = await storage.ContainKeyAsync(authStorageKey);
>         if (exists)
>         {
>             var str = await storage.GetItemAsStringAsync(authStorageKey);
>             return JsonConvert.DeserializeObject<Session>(str);
>         }
>         return null;
>     }
> };
> Supabase.Client.Initialize(url, key, options);
> 
> await host.RunAsync();
> ```
> 
> The `AuthenticationStateProvider` can be adjusted to use the singleton built in to the Supabase Client:
> 
> **SupbaseAuthStateProvider.cs**
> 
> ```cs
> public class SupabaseAuthStateProvider : AuthenticationStateProvider
>     {
>         public override Task<AuthenticationState> GetAuthenticationStateAsync()
>         {
>             var tokenHandler = new JwtSecurityTokenHandler();
>             var identity = new ClaimsIdentity();
>             var instance = Supabase.Client.Instance; // <----
>             var token = instance?.Auth?.CurrentSession?.AccessToken ?? "";
> 
>             if (tokenHandler.CanReadToken(token))
>             {
>                 var jwtSecurityToken = tokenHandler.ReadJwtToken(token);
>                 identity = new ClaimsIdentity(jwtSecurityToken.Claims, "jwt");
>             }
> 
>             var principal = new ClaimsPrincipal(identity);
>             var authenticationState = new AuthenticationState(principal);
>             var authenticationTask = Task.FromResult(authenticationState);
> 
>             return authenticationTask;
>         }
>     }
> ```
> 
> As for the `Wrapper` class you wrote, you should just reference `Supabase.Client.Instance` directly, because it is already a singleton - otherwise that code in there should work just fine for you!

That's Great
Thanks a lot, I'll do try in the next days I'll be back with a feedback

Diego
