### ISSUE TITLE
how to correctly format jsonb fields?

### ISSUE THREAD

**Issue by ajonno** [supabase-community/supabase-csharp#30]
hey all, im having some probs with ```jsonb``` fields and getting data in to the field in the correct format.

eg. ive tried setting the model type as "string", but every time I write to a row in the table, the entry in the jsonb field is a string literal with ie. quotes "xx" either side. this prevents using jsonb functions like ```jsonb_to_recordset(xxx)```

I'm trying to get an array of objects into the ```jsonb``` field. 
eg. [ {"field1": 123, "field2": "someval"}, .... ]

should I use a different model data type instead of "string" ? 

```
        [Postgrest.Attributes.Column("people")]
        public string? People { get; set; } <========== string isn't working
```

really appreciate if u can let me know correct way to format this. this would be great one to add to examples on the README too I reckon.

**Comment by acupofjose** [comment]
Sure! I believe using `Dictionary<string, object>` or `object` as your type and it should make it deserialize/serialize correctly.

**Comment by ajonno** [comment]
doh ! ```List<Dictionary<string, object>>``` did the trick thanks!

**Comment by ajonno** [comment]
quick related question - I assume that with the C# api its not possible to achieve things the same as you would if you we're using ```jsonb``` helper functions in pure psql ?

eg.
```
select * 
from award_show_nominee,
jsonb_to_recordset(award_show_nominee.people) as items(person_name text, as_a text)
where person_name = 'Jared Bush'
```

in the above example, 'Jared Bush' is a value embedded in a ```jsonb``` object array.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/3005269/182510814-e579a50a-6c6f-4f95-9da4-682f517d0572.png">


ie ```jsonb_to_recordset``` isn't available via the C# query api ?

**Comment by acupofjose** [comment]
Hm. The library is meant to mirror as much functionality as [PostgREST](https://postgrest.org/en/stable/index.html) offers. It looks like they support this? I don't have the time to spin up an example to poke around with at the moment, but you could try here getting the C# API calls to generate something like this:
https://postgrest.org/en/stable/api.html?highlight=json#json-columns

**Comment by ajonno** [comment]
sure thing, no worries ill play around and see if I can figure it out 👍
