### ISSUE TITLE
Testing Supabase Example

### ISSUE THREAD

**Issue by andresud** [supabase-community/supabase-csharp#33]
Hello Guys,

I just download the project and try to run the SupabaseExample and got this error:

System.UriFormatException: 'Invalid URI: The Authority/Host could not be parsed.'

I'm using my correct SUPABASE_URL / SUPABASE_KEY....

Am I missing something?

Thank you

**Comment by acupofjose** [comment]
Not much I can do to debug with that information unfortunately:

Url should look like: `https://XXXXXXXXXXXXXX.supabase.co`
And key should be your `public_key` or `service_key` (depending on usage)

Is that what you've got? Based on the error, it sounds like the URL is incorrect.

**Comment by andresud** [comment]
Sorry that I didn't share more details.
I didn't change anything, just added my SUPABASE_URL / SUPABASE_KEY as env vars rebuild the project and run.

launchSettings.json
{
  "profiles": {
    "SupabaseExample": {
      "commandName": "Project",
      "environmentVariables": {
        "SUPABASE_URL": "https:/xmmdsfpofzgxvouqkmjl.supabase.co",
        "SUPABASE_KEY": "my-public-key that I don't want to share to public :D"
      }
    }
  }
}

Thank you, Joseph.

**Comment by acupofjose** [comment]
Happy to help! Looks like you’re missing a forward slash in your supabase URL there!
