### ISSUE TITLE
Enable nullability in the project and make use of nullable reference types.

### ISSUE THREAD

**Issue by StarlkYT** [supabase-community/supabase-csharp#34]
## Is your feature request related to a problem? Please describe.
NRTs help developers to avoid NREs.

## Describe the solution you'd like
To basically annotate anything that is nullable.

**Comment by acupofjose** [comment]
@StarlkYT I think this would be a great improvement to the project. I'm in the process of doing a rewrite of each of the libraries to a Dependency Injection structure for the next major version, and I will include this as on of the issues for it!
