### ISSUE TITLE
Storage upload using service role

### ISSUE THREAD

**Issue by rr-code-base** [supabase-community/supabase-csharp#44]
# Uploading to file storage when using service role api keys not working as expected

Tried uploading a file using the upload method from the examples and I wasn't getting any exceptions and even got a public url back but when I checked the storage bucket in supabase there was no file there. Then I adding the code to check if the bucket existed and then I got a bad request exception with "Invalid JWT" error. I was able to perform other supabase queries prior to getting to the upload step using the service role with no issues.

**Comment by acupofjose** [comment]
@rr-code-base 

I'm struggling to duplicate - I've tried the following code on an existing and a new project:

```c#
var url = "URL";
var key = "SERVICE_ROLE_KEY";
var supabase = new Supabase.Client(url, key);
await supabase.InitializeAsync();

var storage = supabase.Storage;

var exists = await storage.GetBucket("testing") != null;
if (!exists)
    await storage.CreateBucket("testing", new BucketUpsertOptions { Public = true });

var buckets = await storage.ListBuckets();

var bucket = storage.From("testing");
var basePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().CodeBase).Replace("file:", "").Replace("C:\\", "");
var imagePath = Path.Combine(basePath, "Assets", "supabase-csharp.png");

Debug.WriteLine(await bucket.Upload(imagePath, "supabase-csharp.png", new FileOptions { Upsert = true }, (sender, args) => Debug.WriteLine($"Upload Progress: {args}%")));
Debug.WriteLine(bucket.GetPublicUrl("supabase-csharp.png"));
Debug.WriteLine(await bucket.CreateSignedUrl("supabase-csharp.png", 3600));

var bucketItems = await bucket.List();

foreach (var item in bucketItems)
    Debug.WriteLine($"[{item.Id}] {item.Name} - {item.CreatedAt}");

Debug.WriteLine(await bucket.Download("supabase-csharp.png", Path.Combine(basePath, "testing-download.png"), (sender, args) => Debug.WriteLine($"Download Progress: {args}%")));
```

I do get a 401 error when trying to create if I'm not using the service role key. Are you using the supabase client for both user and admin roles? If so, try separating them into different instances?

**Comment by rr-code-base** [comment]
I split into different instances and it is working now.

Thanks for your help!

**Comment by acupofjose** [comment]
Perfect. Happy to help!
