### ISSUE TITLE
.Net 6 Blazor not using CustomAuthStateProvider 

### ISSUE THREAD

**Issue by BlueWaterCrystal** [supabase-community/supabase-csharp#59]
Hi,

I can't seem to get C# Blazor (.Net 6) to work.

It doesn't seem to use CustomAuthStateProvider so `.User.Identity.IsAuthenticated` always returns false.

if I change AuthenticationStateProvider in AuthService.cs to CustomAuthStateProvider, it can authenticate but then the pages can't detect it so returns unauthenticated.

```
builder.Services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>(
    provider => new CustomAuthStateProvider(
        provider.GetRequiredService<ILocalStorageService>(),
        provider.GetRequiredService<Supabase.Client>(),
        provider.GetRequiredService<ILogger<CustomAuthStateProvider>>()
    )
);
```

**Comment by acupofjose** [comment]
@rhuanbarros could you give your thoughts?

**Comment by BlueWaterCrystal** [comment]
Services were in the wrong order in the program.cs

**Comment by rhuanbarros** [comment]
I got here too late. 🥲

**Comment by rhuanbarros** [comment]
> @rhuanbarros could you give your thoughts?

I got here too late. 🥲

**Comment by acupofjose** [comment]
Ha! No worries - thanks for being here!
