### ISSUE TITLE
System.NullReferenceException with "Where" method

### ISSUE THREAD

**Issue by TaakkoA** [supabase-community/supabase-csharp#63]
# Me stupid 

## Describe the bug
Me stupid. Me practicing using supabase. Me confused. Stupid machine.

Me use Supabase. Me have problem with IPostgrestTable. Me try use 'Where' method, but it no work. Me get big error message that say 'System.NullReferenceException'. Me no understand why. Me wonder if me miss something important. Anyone know what me do wrong

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

        public async Task<Query<bool, UserRow>> DeleteUsers(HashSet<long> userIds)
        {
            if (userIds == null || userIds.Count == 0)
                return Query<bool, UserRow>.Failed(false, null, "UserIds was null or empty");

            if (_supabase == null)
                return Query<bool, UserRow>.Failed(false, null, ClientNullMessage);

            try
            {
                Expression<Func<UserRow, bool>> myExpression = (UserRow u) => userIds.Contains(u.Id);
                await _supabase.From<UserRow>().Where(myExpression).Delete();
                string messsage = Logger.Log(LogMessageType.Info, $"Successfully deleted {userIds.Count} user(s).");
                return Query<bool, UserRow>.Success(true, null, messsage);
            }
            catch (Exception ex)
            {
                string messsage = Logger.Log(LogMessageType.Error, $"An error occurred while deleting user rows: {ex.Message}");
                return Query<bool, UserRow>.Failed(false, null, messsage);
            }
        }

## Expected behavior
Me want to get rid of all the user thingies in the HashSet. How me do that?
## Screenshots

![image](https://user-images.githubusercontent.com/53443679/230545153-a2a74525-2af1-4a51-9563-aaaa6e23e60b.png)

## Additional context

![image](https://user-images.githubusercontent.com/53443679/230545499-4c7caa48-dec3-4fbf-ba76-16a44ca0d266.png)

**Comment by acupofjose** [comment]
Try using the `Filter` and `Operator.In` clause instead.

Maybe:
```c#
// Example data
var set = new HashSet<long>() { 1234, 5678, 9101112 };

// Verify that the query returns the expected data
var query = await client.Table<Message>()
                .Filter(x => x.ChannelId, Constants.Operator.In, set)
                .Get();
```

The LINQ clauses are setup to filter things server side - so, unfortunately, there's not a LINQ parser set up to pass a hashset's values in the way you are doing currently. The `Filter` setup above should produce the result you're looking for!
