### ISSUE TITLE
Can't Use Where Clause With Enums.

### ISSUE THREAD

**Issue by h4ckitt** [supabase-community/supabase-csharp#66]
# Bug report

## Describe the bug

I Have An Enum
```c#
public enum Status {Approved, Declined, Pending}
```

And A Class
```c#
[Table("request")]
public class Request {
   [PrimaryKey("id")]
   public string id {get; set;}
   [Column("name")]
   public string Name {get; set;}
   [Column("status")]
   public Status status = Status.Pending;
}
```

I Can Insert The Status Into The Database Alright, But When Trying To Retrieve Data From he Database Like So

```c#
  _client.From<Request>.Where(x => x.id == "1" && x.Status == Status.Pending).Single().Result;
```

I Get The Following Error:
`Left side of expression: '(Convert(x.Status, Int32) == 2)' is expected to be property with a ColumnAttribute or PrimaryKeyAttribute`

The Annotations Are Present And Correct.

I'll Appreciate Any Help I Can Get, Thanks.

## To Reproduce

Described Above

## Expected behavior

Fetch Record From The DB Whose Id And Status Matches The Specification Provided.

## System information

- OS: Linux
- Browser: N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by acupofjose** [comment]
Thanks for the bug report! You're right. Enum expressions aren't supported by the LINQ parser at the moment. I'm finding that they're a little hard to type (since they're all considered their own type). But! Since postgrest-csharp is built on top of JSON.net - you can do the following:

Declare your parse-able members like this:
```c#
[JsonConverter(typeof(StringEnumConverter))]
public enum Status
{
	[EnumMember(Value = "Approved")]
	APPROVED,
	[EnumMember(Value = "Declined")]
	DECLINED,
	[EnumMember(Value = "Pending")]
	PENDING,
}
```

To query on it, you can use the following helper:
```c#
public string? GetEnumMemberAttrValue<T>(T enumVal)
{
	var enumType = typeof(T);
	var memInfo = enumType.GetMember(enumVal.ToString());
	var attr = memInfo.FirstOrDefault()?.GetCustomAttributes(false).OfType<EnumMemberAttribute>().FirstOrDefault();
	if (attr != null)
	{
		return attr.Value;
	}
	return null;
}
```

And write a query using `Filter` instead of `Where`:
```c#
var todos = await client.Table<Todo>()
    .Filter(x => x.Status, Operator.Equals, GetEnumMemberAttrValue(Status.APPROVED))
    .Get();
```

**Comment by h4ckitt** [comment]
Hello,

Thank You Very Much For The Very Speedy Reply.

I Also Tried The Filter But It  Didn't Work At The Time.

The Solution You Proposed Worked For Me And I'm Really Grateful For That.

Although When I Try To Insert A Request Object, The Int Value Of The Enum Field Gets Written Instead Of The String Value And I Don't Know How To Enforce Insertion Of The String Representation Instead Of The Int Representation.

Thank You Very Much For Your Time.

**Comment by Realprach** [comment]
npm run dev

**Comment by elrhomariyounes** [comment]
Hello @acupofjose it's been a while hope you're doing great. I'm a bit rusty but I submitted a PR in postgrest repo to fix this. Please let me know if I missed something or I need to something more.
