### ISSUE TITLE
Assembly Naming

### ISSUE THREAD

**Issue by Kuffs2205** [supabase-community/supabase-csharp#74]
Some of the assemblies have pretty generic names. i.e Functions.dll

Would it be possible to rename them using the Supabase namespace e.g. Supabase.Functions.dll so there is less chance of conflict with other libraries who name similarly.

**Comment by acupofjose** [comment]
Good idea - Available in 0.11.1!

**Comment by Kuffs2205** [comment]
Excellent. Thank you.

**Comment by acupofjose** [comment]
Yep!
