### ISSUE TITLE
Please Add proguard rules

### ISSUE THREAD

**Issue by kaushalkumar86** [supabase-community/supabase-csharp#87]
# Proguard Rules

##Worked fine in developer mode, but as soon as I introduced proguard, got null oject refences

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses

**Comment by wiverson** [comment]
Are you using Unity? I ran into issues with Unity code stripping and JSON breaking due to constructors getting wiped out. My current workaround is to turn stripping off.

**Comment by kaushalkumar86** [comment]
Yes, using unity,
I added those line in proguard rules and everything is working fine now.

**Comment by wiverson** [comment]
@kaushalkumar86 Hey, when you get a chance can you post the specific rules you used?

**Comment by kaushalkumar86** [comment]
Hello @wiverson ,
I already mentioned the proguard rules I used earlier.
Anyways,

-keepattributes Signature
-keepattributes Annotation
-keepattributes EnclosingMethod
-keepattributes InnerClasses

These rules I used to make it work. Also, make sure u have internet property set as "required" in unity player settings, as I was getting errors if not set as required (For android development).

**Comment by wiverson** [comment]
Thanks!
