### ISSUE TITLE
Windows Forms Applications??

### ISSUE THREAD

**Issue by ali-alsheakh** [supabase-community/supabase-csharp#9]
Will it be supported soon?
I've Tried to use NUGET Packages But It Seems Like There Is Some Problems In The Targeted .NET Framework

Error :Could not install package 'supabase-csharp 0.1.9'.
 You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.

**Comment by acupofjose** [comment]
@ali-alsheakh I'm working on setting the target framework to `netstandard2.0` for all of the csharp libraries - which should fix your problem! I'll let you know when I'm done. Thanks for the issue!

**Comment by acupofjose** [comment]
Available in v0.2.0!
